services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile from the root
    container_name: fastapi_app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - ./application:/code/application
    expose:
      - 8000
    command: >
      sh -c "
      cd /code/application/db;
      alembic upgrade head;
      cd /code;
      uvicorn application.main:app --host 0.0.0.0 --port 8000 --reload" 

  db:
    image: postgres:17.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - ./application/db/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1
    container_name: redis
    expose:
      - 6379

  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  postgres_data: